theme: jekyll-theme-modernist
title: AUTOSURF-PES-rigid4D
description: A code for the automated construction of potential energy surfaces for van der Waals systems composed of two (rigid) linear fragments.
